services:
   web:
      build: .
      container_name: app
      ports:
       - "443:8080"
      links:
       - db
   db:
      image: mongo
      container_name: mongodb
      ports:
        - 27017:27017
